### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'local_scope'

### ISSUE THREAD

**Issue by lixinyuu** [tencent-alchemy/Alchemy#14]
Hi,

I am testing the dgl MPNN model. However, it ended with error
```
Traceback (most recent call last):
  File "train.py", line 74, in <module>
    train(args.model, int(args.epochs), device)
  File "train.py", line 48, in train
    res = model(batch.graph)
  File "/home/xl9541/pythonenv/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xl9541/tencent_alchemy/mpnn/mpnn.py", line 138, in forward
    out = self.set2set(out, g)
  File "/home/xl9541/pythonenv/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "//home/xl9541/pythonenv/pytorch/lib/python3.6/site-packages/dgl/nn/pytorch/glob.py", line 273, in forward
    with graph.local_scope():
AttributeError: 'Tensor' object has no attribute 'local_scope'
```
It looks like the dgl graph lost this "local_scope" information. Could anyone give me some suggestions on this?

Thanks,
xy

**Comment by mufeili** [comment]
We interchanged the order of `out` and `g` for the input of nn modules in the latest release, which causes this error. I'll PR a fix. If urgent, just replace `self.set2set(out, g)` with `self.set2set(g, out)`.

**Comment by lixinyuu** [comment]
Thanks, Mufei.

**Comment by Soontosh** [comment]
I've also just gottend this error: https://discuss.dgl.ai/t/attributeerror-tensor-object-has-no-attribute-local-scope/4494
